from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Iterable


def sanitize_file_stem(value: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", value).strip(" .")
    cleaned = re.sub(r"\s+", "_", cleaned)
    return cleaned[:100] or "IES_OUTPUT"


def _format_number(value: float, decimals: int | None = None) -> str:
    if decimals is not None:
        return f"{value:.{decimals}f}"
    if float(value).is_integer():
        return str(int(value))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def _wrapped(values: Iterable[float], per_line: int = 10, decimals: int | None = None) -> list[str]:
    rendered = [_format_number(value, decimals) for value in values]
    return [" ".join(rendered[i : i + per_line]) for i in range(0, len(rendered), per_line)]


class IESWriter:
    @staticmethod
    def write(scaled_data: dict[str, Any], output_path: str | Path) -> str:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        header = [line for line in scaled_data["header_lines"] if not line.startswith("[MORE] Generated by IES Scaling Tool")]
        notes = [
            "[MORE] Generated by IES Scaling Tool. ESTIMATED.",
            "[MORE] This file is estimated from measured IES data by luminous-flux scaling.",
            "[MORE] For preliminary lighting simulation only.",
            "[MORE] Not a certified photometric test report.",
            f"[MORE] Scale factor: {scaled_data['scale_factor']:.4f}",
            f"[MORE] Source luminous flux: {_format_number(scaled_data['source_luminous_flux_lm'])} lm",
            f"[MORE] Target luminous flux: {_format_number(scaled_data['target_luminous_flux_lm'])} lm",
            f"[MORE] Target power: {_format_number(scaled_data['target_power_w'])} W",
        ]
        if scaled_data.get("centering_note"):
            notes.append(f"[MORE] {scaled_data['centering_note']}")
        if "target_luminous_length_mm" in scaled_data:
            notes.append(f"[MORE] Target luminous length: {_format_number(scaled_data['target_luminous_length_mm'])} mm")
        if "target_luminous_width_mm" in scaled_data:
            notes.append(f"[MORE] Target luminous width: {_format_number(scaled_data['target_luminous_width_mm'])} mm")
        first_numeric = [
            scaled_data["number_of_lamps"], scaled_data["lumens_per_lamp"], scaled_data["candela_multiplier"],
            scaled_data["num_vertical_angles"], scaled_data["num_horizontal_angles"], scaled_data["photometric_type"],
            scaled_data["units_type"], scaled_data["width"], scaled_data["length"], scaled_data["height"],
        ]
        second_numeric = [
            scaled_data["ballast_factor"], scaled_data["future_use"], scaled_data["target_power_w"]
        ]
        lines = [scaled_data["ies_version"], *header, *notes, "TILT=NONE"]
        lines.append(" ".join(_format_number(float(v)) for v in first_numeric))
        lines.append(" ".join(_format_number(float(v)) for v in second_numeric))
        lines.extend(_wrapped(scaled_data["vertical_angles"]))
        lines.extend(_wrapped(scaled_data["horizontal_angles"]))
        for row in scaled_data["candela_values"]:
            lines.extend(_wrapped(row, decimals=3))
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return str(path)
